# Generated by Django 5.2.3 on 2025-06-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_alter_formation_institution_alter_formation_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
