# Generated by Django 5.2.3 on 2025-07-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_formation_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
