# Generated by Django 5.2.3 on 2025-07-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_formation_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='type',
            field=models.CharField(choices=[('online', 'En ligne'), ('in-person', 'En personne')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
