# Generated by Django 5.2.3 on 2025-07-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobType',
            field=models.CharField(choices=[('Full-Time', 'Temps plein'), ('Part-Time', 'Temps partiel'), ('Internship', 'Stage'), ('Remote', 'Télétravail'), ('Contract', 'Contractuel')], default='Full-Time', max_length=20),
        ),
    ]
